# Generated by Django 5.1.4 on 2025-01-24 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dr', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('idDr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.dr')),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.consult')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('consult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='history.consult')),
            ],
        ),
    ]
