# Generated by Django 5.1.4 on 2025-01-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('last_name', models.TextField()),
                ('dni', models.TextField()),
                ('birth_date', models.DateField()),
                ('gender', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('observations', models.TextField()),
            ],
        ),
    ]
